source 'https://rubygems.org'

gem 'rails', '4.0.4.rc1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'byebug'
gem 'pry-byebug'

gem 'synchronizable', path: '../../'
